kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/ironcore864/tap

steps:
- name: test
  image: golang
  commands:
  - go get ./...
  - go test ./...
  - go build
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: ironcore864/tap
    tags: latest
